
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import tkinter as tk
from tkinter import messagebox
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/arnavkanwar/Desktop/SQL/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

user_data = {
    "user1": "password1",
    "user2": "password2",
    "admin": "adminpass"
}

# Function to handle login
def login():
    username = entry_1.get()
    password = entry_2.get()
        # Check if the username exists and the password matches
    if username in user_data and user_data[username] == password:
       messagebox.showinfo("Login Success", f"Welcome, {username}!")
    else:
        messagebox.showerror("Login Failed", "Invalid username or password.")

window = Tk()

window.geometry("1024x768")
window.configure(bg = "#71878F")


canvas = Canvas(
    window,
    bg = "#71878F",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    209.0,
    436.0,
    image=image_image_1
)

canvas.create_rectangle(
    410.0,
    182.0,
    994.0,
    727.0,
    fill="#9AB0B8",
    outline="")

canvas.create_rectangle(
    20.0,
    26.0,
    994.0,
    146.0,
    fill="#98ADB6",
    outline="")

canvas.create_text(
    20.0,
    26.0,
    anchor="nw",
    text="LAUNDRY MANAGEMENT SYSTEM",
    fill="#0C0303",
    font=("Roboto ExtraBold", 50 * -1,)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    719.0,
    387.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
)
entry_1.place(
    x=529.0,
    y=362.0,
    width=380.0,
    height=48.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    719.0,
    571.5,
    image=entry_image_2
)
entry_2 = Entry(
    window,
    show="*",
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=529.0,
    y=546.0,
    width=380.0,
    height=49.0
)

canvas.create_text(
    549.0,
    270.0,
    anchor="nw",
    text="USERNAME",
    fill="#150404",
    font=("Roboto ExtraBold", 60 * -1)
)

canvas.create_text(
    558.0,
    454.0,
    anchor="nw",
    text="PASSWORD",
    fill="#160303",
    font=("Roboto ExtraBold", 60 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=login,
    relief="flat"
)
button_1.place(
    x=644.0,
    y=633.0,
    width=150.0,
    height=40.0,
  
)
window.resizable(False, False)
window.mainloop()
