
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/arnavkanwar/Desktop/SQL/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    240.0,
    402.0,
    image=image_image_1
)

canvas.create_rectangle(
    23.0,
    25.0,
    1002.0,
    130.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    41.0,
    45.0,
    anchor="nw",
    text="TRACKING STATUS",
    fill="#000000",
    font=("Inter", 60 * -1)
)

canvas.create_rectangle(
    552.0,
    223.0,
    992.0,
    594.0,
    fill="#89A1AB",
    outline="")

canvas.create_rectangle(
    608.0,
    276.0,
    936.0,
    370.0,
    fill="#59A8D8",
    outline="")

canvas.create_text(
    608.0,
    301.0,
    anchor="nw",
    text="YOUR STATUS",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_rectangle(
    608.0,
    439.0,
    936.0,
    527.0,
    fill="#85BBDB",
    outline="")
window.resizable(False, False)
window.mainloop()
